"""Consumed aioftp 0.21.3 API; checked against real FTP integration tests."""
from collections.abc import AsyncIterator, Callable, Coroutine, Iterable
from contextlib import AbstractAsyncContextManager
from os import stat_result
from pathlib import Path, PurePosixPath
from typing import Any, ParamSpec, TypeVar
from types import TracebackType
from asyncio import Task

P = ParamSpec("P")
R = TypeVar("R")

class ThrottleStreamIO(AbstractAsyncContextManager["ThrottleStreamIO"]):
    async def __aexit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, traceback: TracebackType | None) -> None: ...
    async def write(self, data: bytes) -> None: ...

class AsyncFile(AbstractAsyncContextManager["AsyncFile"]):
    async def __aexit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, traceback: TracebackType | None) -> None: ...
    async def seek(self, offset: int) -> int: ...
    def iter_by_block(self, count: int) -> AsyncIterator[bytes]: ...

class AsyncPathIO:
    async def stat(self, path: Path) -> stat_result: ...
    def open(self, path: Path, mode: str = ...) -> AsyncFile: ...

class Connection:
    path_io: AsyncPathIO
    data_connection: ThrottleStreamIO
    restart_offset: int
    block_size: int
    extra_workers: set[Task[None]]
    def response(self, code: str, lines: str) -> None: ...

class User:
    def __init__(self, login: str, password: str, *, base_path: str | Path, permissions: Iterable[Permission] = ..., maximum_connections: int | None = ...) -> None: ...

class Permission:
    def __init__(self, path: str, *, readable: bool = ..., writable: bool = ...) -> None: ...

class Server:
    commands_mapping: dict[str, Callable[[Connection, str | PurePosixPath], Coroutine[Any, Any, bool]]]
    server_port: int
    def __init__(self, users: Iterable[User] | None = ..., **kwargs: Any) -> None: ...
    async def start(self, host: str, port: int) -> None: ...
    async def close(self) -> None: ...
    async def parse_command(self, stream: ThrottleStreamIO, censor_commands: tuple[str, ...] = ...) -> tuple[str, str]: ...
    def get_paths(self, connection: Connection, rest: str | PurePosixPath) -> tuple[Path, PurePosixPath]: ...

class ConnectionConditions:
    login_required: tuple[str, str]
    passive_server_started: tuple[str, str]
    data_connection_made: tuple[str, str]
    def __init__(self, *fields: tuple[str, str], wait: bool = ..., fail_code: str = ..., fail_info: str | None = ...) -> None: ...
    def __call__(self, func: Callable[P, R]) -> Callable[P, R]: ...

class PathConditions:
    path_must_exists: Callable[..., object]
    path_must_be_file: Callable[..., object]
    def __init__(self, *conditions: Callable[..., object]) -> None: ...
    def __call__(self, func: Callable[P, R]) -> Callable[P, R]: ...

class PathPermissions:
    readable: Callable[..., object]
    def __init__(self, *permissions: Callable[..., object]) -> None: ...
    def __call__(self, func: Callable[P, R]) -> Callable[P, R]: ...
